flow:
  nu: 0.01
  initialVelocity: [0.0, 0.0]
  boundaryConditions:
    - location: xMinus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]
    - location: xPlus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]
    - location: yMinus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]
    - location: yPlus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]

mesh:
  - direction: x
    start: -4.0
    subDomains:
      - end: 4.0
        cells: 512
        stretchRatio: 1.0
  - direction: y
    start: -4.0
    subDomains:
      - end: 4.0
        cells: 512
        stretchRatio: 1.0

parameters:
  dt: 0.002
  startStep: 0
  nt: 10000
  nsave: 100
  nrestart: 5000
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  delta: PESKIN_2002
  velocitySolver:
    type: CPU
    config: config/velocity_solver.info
  poissonSolver:
    type: GPU
    config: config/poisson_solver.info
  forcesSolver:
    type: CPU
    config: config/forces_solver.info

bodies:
  - type: points
    name: "circle"
    file: circle.body
    kinematics:
      KC: 5.0
      D: 1.0
      f: 0.2
      center: [0.0, 0.0]
