mesh:
  - direction: x
    start: 0.0
    subDomains:
      - end: 1.0
        cells: 20
        stretchRatio: 1.0
  - direction: y
    start: 0.0
    subDomains:
      - end: 1.0
        cells: 20
        stretchRatio: 1.0

flow:
    nu: 0.01
    initialVelocity: [0.0, 0.0]
    boundaryConditions:
      - location: xMinus
        u: [DIRICHLET, 0.0]
        v: [DIRICHLET, 0.0]
      - location: xPlus
        u: [DIRICHLET, 0.0]
        v: [DIRICHLET, 0.0]
      - location: yMinus
        u: [DIRICHLET, 0.0]
        v: [DIRICHLET, 0.0]
      - location: yPlus
        u: [DIRICHLET, 1.0]
        v: [DIRICHLET, 0.0]

parameters:
    dt: 5.0E-04
    startStep: 0
    nt: 500
    nsave: 500
    nrestart: 500
    convection: EULER_EXPLICIT
    diffusion: EULER_IMPLICIT
    velocitySolver:
      type: CPU
      config: ../configs/solversPetscOptions.info
    poissonSolver:
      type: CPU
      config: ../configs/solversPetscOptions.info
